# Generated by Django 4.0.5 on 2022-06-30 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('school', models.CharField(choices=[('Sciences_&_computing', 'Sciences_&_computing'), ('Education', 'Education'), ('Health', 'Health')], default='science_&_computing', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.departments')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('reg_no', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/images/students')),
                ('school', models.CharField(choices=[('Sciences_&_computing', 'Sciences_&_computing'), ('Education', 'Education'), ('Health', 'Health')], default='science_&_computing', max_length=30)),
                ('date_of_admission', models.DateField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.departments')),
            ],
        ),
    ]
