# Generated by Django 4.0.5 on 2022-06-30 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='units',
            name='school',
            field=models.CharField(choices=[('Semester1', 'Semester1'), ('Semester2', 'Semester2'), ('Semester3', 'Semester3')], default='Semester1', max_length=30),
        ),
        migrations.AlterField(
            model_name='departments',
            name='school',
            field=models.CharField(choices=[('SAFS', 'SAFS'), ('SBE', 'SBE'), ('SCI', 'SCI'), ('SEA', 'SEA'), ('SED', 'SED'), ('SHS', 'SHS'), ('SON', 'SON'), ('SPAS', 'SPAS'), ('TVET', 'TVET')], default='SBE', max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.CharField(choices=[('SAFS', 'SAFS'), ('SBE', 'SBE'), ('SCI', 'SCI'), ('SEA', 'SEA'), ('SED', 'SED'), ('SHS', 'SHS'), ('SON', 'SON'), ('SPAS', 'SPAS'), ('TVET', 'TVET')], default='science_&_computing', max_length=30),
        ),
    ]
