# Generated by Django 4.0.5 on 2022-06-30 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_units_school_alter_departments_school_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='units',
            old_name='school',
            new_name='semester',
        ),
    ]
